apiVersion: apps/v1
kind: Deployment
metadata:
  name: mentoring-deployment
  namespace: gerald-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mentoring-app
  template:
    metadata:
      labels:
        app: mentoring-app
    spec:
      containers:
      - name: container-mentoring
        image: PLEASE_REPLACE_ME
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000