apiVersion: v1
kind: Service
metadata:
  name: mentoring-service
  namespace: gerald-env
spec:
  selector:
    app: mentoring-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32313
  type: NodePort